In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.shape

(5572, 2)

In [4]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [5]:
# Manual encoding for Category 'ham' == 0 & 'spam' == 1
df.Category = df.Category.replace(['ham', 'spam'], [0, 1])

In [6]:
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [7]:
X = df['Message']
y = df['Category']

In [8]:
# Count vector encodig for Message
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
cv = CountVectorizer()

In [10]:
X = cv.fit_transform(X)

In [11]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
# Data train test split
from  sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [14]:
# Appling MultinomialNB algoritm
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

In [15]:
mnb.fit(X_train, y_train)

MultinomialNB()

In [16]:
mnb.score(X_test, y_test)

0.979066985645933

In [17]:
email = ['hi my name is badhan saha.', 'you win iphone x.please click the link bellow.']

In [18]:
cv_test = cv.transform(email)

In [19]:
mnb.predict(cv_test)

array([0, 1], dtype=int64)

In [20]:
# Measuring the preformance of the algorithm
predict = mnb.predict(X_test)
predict

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
# Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predict)

0.979066985645933

In [22]:
# Using confusion matrix
from sklearn.metrics import confusion_matrix

In [23]:
confusion_matrix(y_test, predict)

array([[1442,   22],
       [  13,  195]], dtype=int64)

In [24]:
# Classification report
from sklearn.metrics import classification_report

In [25]:
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      1464
           1       0.90      0.94      0.92       208

    accuracy                           0.98      1672
   macro avg       0.94      0.96      0.95      1672
weighted avg       0.98      0.98      0.98      1672

